"use client";
import {useState} from 'react';
import {api,validateResult,type SavedResult,type SavedRecipe} from '@/lib/dinner-scout/http-service';
import type {ProgressEvent} from '@/lib/dinner-scout/types';
const reasons:Record<string,string>={no_eligible_candidates:'The imported recipes still need cooking time, quantities, nutrition or allergen verification.',nosana_endpoint_not_ready:'Nosana inference is not connected.',nosana_preparation_required:'Nosana needs a verified warm inference service.',nosana_preparation_failed:'Nosana preparation has not succeeded.',nosana_inference_failed:'Nosana did not return a verified selection.',purchase_price_or_weight_unknown:'Purchase prices or package weights are still unknown.'};
const money=(v:number|null)=>v===null?'Unknown':`¥${v.toLocaleString('en-US')}`;
export default function SavedResults({event,result,error,onBack,onResult}:{event?:ProgressEvent;result?:SavedResult;error:string;onBack:()=>void;onResult:(r:SavedResult)=>void}){
 const [choices,setChoices]=useState<SavedRecipe[]>([]);const [day,setDay]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [swapError,setSwapError]=useState('');
 async function openSwap(index:number){if(!result)return;setBusy(true);setDay(index);setSwapError('');try{const x=await api<{alternatives:SavedRecipe[]}>(`/runs/${result.runId}/alternatives`);setChoices(x.alternatives)}catch(e){setSwapError((e as Error).message)}finally{setBusy(false)}}
 async function replace(recipeId:string){if(!result||day===null)return;setBusy(true);try{onResult(validateResult(await api(`/runs/${result.runId}/swap`,{method:'POST',body:JSON.stringify({day,recipeId,revision:result.revision})})));setDay(null);setChoices([])}catch(e){setSwapError((e as Error).message)}finally{setBusy(false)}}
 const events=event?.rawEvents||[];const running=!result&&event?.status!=='failed';
 return <>
  <div className="page-heading"><div><span className="eyebrow">SAVED MATERIALS · REAL PROCESSING</span><h1>{running?'Reading saved recipes.':result?.mealPlan?'Your dinner plan.':'Your source results.'}</h1><p>{running?'Daytona parses your materials, then AuraDB matches ingredients.':'Analysis results are separate from a completed seven-day dinner plan.'}</p></div><button className="secondary" onClick={onBack}>{running?'Cancel':'Edit preferences'}</button></div>
  <div className="demo-strip">Saved sources <span>No live browsing · Unknown values remain unknown</span></div>
  <section className="preference-card" style={{margin:'20px 0',maxWidth:'none'}} aria-live="polite"><h2>Processing progress</h2>{events.length===0?<p>Starting saved-material analysis…</p>:<ol style={{paddingLeft:24}}>{events.map(e=><li key={e.sequence} style={{margin:'6px 0'}}>{e.stage==='document.uploaded'?'Material uploaded':e.stage==='document.parsed'?'Material processed':e.stage==='recipe.parsed'?'Recipe parsed':e.stage==='deal.validated'?'Confirmed offer validated':e.stage==='graph.queried'?'Ingredients matched in AuraDB':e.stage==='selection.started'?'Planning dinners':e.stage==='selection.validated'?'Selection verified':e.stage==='calculation.completed'?'Basket and nutrition calculated':e.stage==='run.blocked'?'Further information needed':e.stage.replaceAll('.',' ')}{e.documentId?` · ${e.documentId}`:''}{e.recipeId?` · ${e.recipeId}`:''}{e.elapsedSeconds!==undefined?` · ${e.elapsedSeconds.toFixed(1)}s`:''}</li>)}</ol>}</section>
  {(error||event?.error)&&<p className="error" role="alert">{error||event?.error}</p>}
  {result&&<>
   {result.stopReasons.length>0&&<div className="warning-banner" role="status"><h2>{result.mealPlan?'Plan needs more information':'Your week is not ready yet'}</h2><ul>{result.stopReasons.map(r=><li key={r}>{reasons[r]||r.replaceAll('_',' ')}</li>)}</ul><p>The verified analysis below is available. No sample meal plan has been substituted.</p></div>}
   <div className="scout-grid">{result.stores?.map(store=><section className="store-card" key={store.id}><h2>{store.name}</h2><p className="hint">Saved store materials</p>{result.deals?.filter(d=>d.storeId===store.id).map(d=><div className="offers" key={d.id}><strong>{d.productName}</strong><p>{money(d.priceYen)} / {d.quantity??'Unknown'} {d.unit??''}</p><p className="hint">Package weight: {d.packGrams===null?'Unknown':`${d.packGrams} g`} · {d.evidence.basis}</p><p className="hint">Valid: {d.validFrom??'Unknown'} — {d.validTo??'Unknown'}</p><a href={d.evidence.sourceUrl} target="_blank" rel="noreferrer">Price source ↗</a></div>)}{!result.deals?.some(d=>d.storeId===store.id)&&<p>No verified offers imported for this store.</p>}</section>)}</div>
   {result.documents&&<section style={{margin:'24px 0'}}><h2>Source previews</h2><p>Original saved materials, not Daytona browser screenshots.</p><div className="chips">{result.documents.map(d=><a className="chip" key={d.documentId} href={'/api/backend'+d.previewUrl.replace(/^\/api/,'')} target="_blank" rel="noreferrer">{d.documentId} · Source preview ↗</a>)}</div></section>}
   <section className="preference-card" style={{maxWidth:'none',margin:'24px 0'}}><h2>Matched recipes · {result.graph?.candidates.length??0} store matches</h2>{result.recipes?.map(r=>{const match=result.graph?.candidates.filter(c=>c.recipeId===r.id)||[];const issues=result.eligibility?.find(e=>e.recipeId===r.id)?.issues||[];return <article key={r.id} style={{padding:'18px 0',borderBottom:'1px solid #e7e2da'}}><h3><a href={r.sourceUrl} target="_blank" rel="noreferrer">{r.title} ↗</a></h3><p>Cooking time: {r.cookingMinutes===null?'Unknown':`${r.cookingMinutes} min`} · Saved Cookpad recipe</p>{match.map(m=><p className="hint" key={m.storeId}>Matching ingredients: {m.matching.join(', ')||'None'}<br/>Additional ingredients: {m.missing.join(', ')||'None'}</p>)}<details><summary>Ingredients and missing information ({issues.length})</summary><ul>{r.requirements.map((q,i)=><li key={i}>{q.raw} · {q.grams===null?'Weight unknown':`${q.grams} g`}</li>)}</ul><ul>{issues.map((x,i)=><li key={i}>{x.field} · {x.status==='unknown'?'Information missing':'Condition not met'}{x.ingredientId?` · ${x.ingredientId}`:''}</li>)}</ul></details></article>})}</section>
   {result.mealPlan&&<section className="preference-card" style={{maxWidth:'none'}}><h2>Dinners and shopping</h2><p>{result.mealPlan.shopping.store.name} · {money(result.mealPlan.shopping.totalYen)} · {result.mealPlan.shopping.totalBasis} · Budget: {result.mealPlan.shopping.budgetStatus}</p>{result.mealPlan.meals.map((meal,i)=><article key={meal.day} style={{padding:12}}><strong>Day {meal.day} · {result.recipes?.find(r=>r.id===meal.recipeId)?.title||meal.recipeId}</strong><p>{Object.entries(meal.nutrition).map(([k,v])=>`${k}: ${v??'Unknown'}`).join(' · ')}</p><button className="secondary" disabled={busy} onClick={()=>openSwap(i)}>Swap</button></article>)}{day!==null&&<div><h3>Choose a different dinner</h3>{choices.map(c=><button className="secondary" key={c.id} disabled={busy} onClick={()=>replace(c.id)}>{c.title}</button>)}{!busy&&!choices.length&&<p>No eligible alternatives available.</p>}<button className="secondary" onClick={()=>setDay(null)}>Close</button></div>}{swapError&&<p role="alert">{swapError}</p>}<ul>{result.mealPlan.shopping.shopping.map(x=><li key={x.ingredientId}>{x.ingredientId} · {x.packs??'Unknown'} packs · {money(x.costYen)}</li>)}</ul></section>}
  </>}
 </>;
}
