import type { Catalog, Ingredient, ProductDeal, Recipe, Store } from "./types";
const ingredient = (
  id: string,
  name: string,
  kcal: number,
  protein: number,
  fat: number,
  carbs: number,
  allergens: string[] = [],
): Ingredient => ({
  id,
  name,
  unit: "g",
  allergens,
  nutrition: { kcal, protein, fat, carbs },
});
// Illustrative nutrition per 100 g, raw weight. Not verified food-label data.
export const ingredients = [
  ingredient("rice", "Rice", 356, 6.1, 0.9, 77),
  ingredient("oil", "Oil", 900, 0, 100, 0),
  ingredient("salt", "Salt", 0, 0, 0, 0),
  ingredient("pepper", "Pepper", 251, 10, 3, 64),
  ingredient("soy", "Soy sauce", 53, 8, 0.1, 5, ["Soy", "Wheat"]),
  ingredient("sugar", "Sugar", 387, 0, 0, 100),
  ingredient("chicken", "Chicken breast", 110, 23, 1.5, 0),
  ingredient("pork", "Lean pork", 145, 21, 6, 0),
  ingredient("salmon", "Salmon", 208, 20, 13, 0, ["Fish"]),
  ingredient("tofu", "Firm tofu", 80, 8, 4, 2, ["Soy"]),
  ingredient("egg", "Eggs", 142, 12, 10, 1, ["Egg"]),
  ingredient("broccoli", "Broccoli", 34, 3, 0.4, 5),
  ingredient("cabbage", "Cabbage", 25, 1.3, 0.1, 6),
  ingredient("mushroom", "Mushrooms", 22, 3, 0.3, 3),
  ingredient("noodles", "Udon noodles", 105, 3, 0.4, 21, ["Wheat"]),
];
export const stores: Store[] = ["A", "B", "C"].map((x) => ({
  id: x,
  name: `Store ${x}`,
}));
const packs: Record<string, [number, number]> = {
  rice: [1000, 780],
  oil: [400, 328],
  salt: [500, 128],
  pepper: [30, 158],
  soy: [500, 228],
  sugar: [500, 198],
  chicken: [400, 358],
  pork: [300, 398],
  salmon: [200, 498],
  tofu: [300, 98],
  egg: [300, 238],
  broccoli: [300, 198],
  cabbage: [500, 158],
  mushroom: [150, 128],
  noodles: [400, 158],
};
export const deals: ProductDeal[] = stores.flatMap((store, s) =>
  ingredients.map((i) => ({
    id: `${store.id}-${i.id}`,
    storeId: store.id,
    ingredientId: i.id,
    name: i.name,
    packGrams: packs[i.id][0],
    price:
      packs[i.id][1] +
      (s === 0 ? 0 : s === 1 ? (i.id === "salmon" ? -40 : 35) : 60),
    mode: "mock" as const,
    source: "sample" as const,
  })),
);
const recipe = (
  id: string,
  name: string,
  main: string,
  grams: number,
  veg: string,
  minutes: number,
  reason: string,
  extra: { ingredientId: string; grams: number }[] = [],
  rice = true,
): Recipe => ({
  id,
  name,
  minutes,
  reason,
  image: `/dinner-scout/${main === "salmon" ? "salmon" : main === "tofu" || main === "egg" ? "tofu" : "chicken"}.jpg`,
  source: "demo",
  ingredients: [
    { ingredientId: main, grams },
    { ingredientId: veg, grams: 100 },
    ...(rice ? [{ ingredientId: "rice", grams: 75 }] : []),
    { ingredientId: "oil", grams: 5 },
    { ingredientId: "soy", grams: 10 },
    ...extra,
  ],
});
export const recipes: Recipe[] = [
  recipe(
    "ginger-chicken",
    "Soy-glazed chicken & rice",
    "chicken",
    180,
    "cabbage",
    20,
    "Chicken breast offer · shares cabbage",
  ),
  recipe(
    "salmon-rice",
    "Pan-seared salmon bowl",
    "salmon",
    170,
    "broccoli",
    25,
    "One salmon pack · broccoli for two dinners",
  ),
  recipe(
    "tofu-egg",
    "Tofu & egg rice bowl",
    "tofu",
    200,
    "mushroom",
    15,
    "Budget-friendly tofu · uses pantry rice",
    [{ ingredientId: "egg", grams: 100 }],
  ),
  recipe(
    "pork-cabbage",
    "Pork & cabbage stir-fry",
    "pork",
    180,
    "cabbage",
    20,
    "Shared cabbage · quick one-pan dinner",
  ),
  recipe(
    "chicken-broccoli",
    "Chicken & broccoli skillet",
    "chicken",
    200,
    "broccoli",
    25,
    "Same chicken pack · a different dinner",
  ),
  recipe(
    "chicken-udon",
    "Chicken & mushroom udon",
    "chicken",
    160,
    "mushroom",
    20,
    "Uses remaining mushrooms",
    [{ ingredientId: "noodles", grams: 200 }],
    false,
  ),
  recipe(
    "tofu-chicken",
    "Chicken & tofu patties",
    "chicken",
    130,
    "cabbage",
    30,
    "Makes the most of tofu",
    [{ ingredientId: "tofu", grams: 100 }],
  ),
  recipe(
    "pork-mushroom",
    "Pork & mushroom rice bowl",
    "pork",
    200,
    "mushroom",
    20,
    "Shared mushrooms · protein-rich pork",
  ),
  recipe(
    "egg-rice",
    "Broccoli & egg fried rice",
    "egg",
    180,
    "broccoli",
    15,
    "Uses pantry rice · low-cost eggs",
  ),
  recipe(
    "tofu-cabbage",
    "Crispy tofu & cabbage",
    "tofu",
    300,
    "cabbage",
    25,
    "A simple plant-based dinner",
  ),
  recipe(
    "salmon-cabbage",
    "Salmon & cabbage skillet",
    "salmon",
    200,
    "cabbage",
    20,
    "Same salmon offer · one pan",
  ),
  recipe(
    "chicken-mushroom",
    "Pepper chicken & mushrooms",
    "chicken",
    220,
    "mushroom",
    20,
    "Chicken offer · extra protein",
  ),
];
export const catalog: Catalog = {
  defaults: {
    budget: 4000,
    protein: 40,
    calories: 650,
    pantry: ["rice", "oil", "salt", "pepper", "soy", "sugar"],
    allergies: [],
    dislikes: [],
  },
  pantry: ingredients.slice(0, 6),
  ingredients,
  allergies: ["Soy", "Wheat", "Fish", "Egg", "Milk", "Peanut", "Shellfish"],
  dislikes: ingredients.slice(6),
  stores,
};
